services:
  grab: 
    image: elena/grab:latest
    security_opt:
      - seccomp:app/src/config/chrome.json
    build: .
    working_dir: /grab
    volumes:
      - ./app:/grab/app
      - ./downloads:/grab/downloads